import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NavBar } from "@/components/NavBar";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-black text-white min-h-screen flex flex-col justify-between w-screen items-center relative">
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
